### read
get http://localhost:3000/players

### read by id
get http://localhost:3000/players/1

### delete
delete http://localhost:3000/players/2

### post
post http://localhost:3000/players
Content-Type: application/json

{
    "name": "Á1111",
    "quantity": 24,
    "price": 2500,
    "type": "tejtermék"
}

### put
put http://localhost:3000/players/apcj3hklbge9fnr
Content-Type: application/json

{
    "name": "<script>alert('betörtem')</script> heló",
    "quantity": 124,
    "price": 3500,
    "type": "kakaótermék"
}
